# Funding links for the Certus project
# These are displayed in the "Sponsor" button on GitHub

# GitHub Sponsors username
github: [oscarvalois]

# Patreon username
# patreon:

# Open Collective username
# open_collective:

# Ko-fi username
# ko_fi:

# Tidelift package name
# tidelift: npm/certus

# Custom sponsorship URLs (up to 4)
# custom: ['https://www.example.com/sponsor']
